[package]
name = "fabushi-android-box-exec-daemon"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
fabushi-android-shared = { path = "../shared" }
fabushi-constants = { path = "../packages/constants" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ureq = { version = "2.12", features = ["json"] }
url = "2"

[lib]
path = "src/lib.rs"
